config/routes.rb
Rails.application.routes.draw do
  get 'briefings', to: 'briefings_earnings#index'

  get 'zacks', to: 'zacks#index'

  get 'new_highs', to: 'new_highs#index'

  get 'all_time_highs', to: 'all_time_highs#index'

  get 'daily_high_lows', to: 'daily_high_lows#index'

  root 'static_pages#home'
end

app/models/all_time_high.rb
class AllTimeHigh < ActiveRecord::Base
  before_validation :blank_field, on: :create
  
  scope :period, -> (time_period) { where("saved_on > ?", time_period) }
  scope :monthly, -> { where("saved_on >  ?", 1.month.ago) }
  scope :by_symbol, -> { group(:symbol) }
  scope :ordered_by, -> { order('count_id DESC').count('id') }

  protected
    def blank_field
      raise 'Empty Field For AllTimeHigh' if self.symbol.blank? || self.saved_on.blank?
    end
end

app/models/briefings_earning.rb
class BriefingsEarning < ActiveRecord::Base

  private
    def self.earnings
      where("earnings > ?", 0)
    end

    def self.expectation
      where("expectation > ?", 0)
    end

    def self.surprise(query)
      where("((earnings - expectation) / expectation) * 100 >= ?", "#{query}")
    end
end

app/models/daily_high_low.rb
class DailyHighLow < ActiveRecord::Base

  private
  def self.reduce_highs(highs, lows)
    highs.zip(lows).map { |h, l| h - l }
  end

  def self.high_low_difference
    sql = "SELECT one_month_high - one_month_low as one_month,
           three_month_high - three_month_low as three_month,
           six_month_high - six_month_low as six_month,
           twelve_month_high - twelve_month_low as twelve_month,
           ytd_high - ytd_low as ytd,
           saved_on
           FROM daily_high_lows
           ORDER BY saved_on DESC;"
    records = ActiveRecord::Base.connection.exec_query(sql)
  end

  def self.high_low_difference_json
  sql = "WITH seqs AS (
         SELECT  json_object_agg(saved_on::text, one_month_high ORDER BY saved_on) one_month_highs,
         json_object_agg(saved_on::text, one_month_low ORDER BY saved_on) one_month_lows
         FROM    daily_high_lows)
         SELECT  json_agg(j)
         FROM    (
         SELECT json_build_object('name', 'One Month Highs', 'data', one_month_highs)
         FROM   seqs
         UNION ALL
         SELECT json_build_object('name', 'One Month Lows', 'data', one_month_lows)
         FROM seqs
         ) x(j)
         ;"
  records = ActiveRecord::Base.connection.exec_query(sql)
  end
end

app/models/new_high.rb
class NewHigh < ActiveRecord::Base
  before_validation :blank_field, on: :create

  scope :period, -> (time_period) { where("saved_on > ?", time_period) }
  scope :monthly, -> { where("saved_on >  ?", 1.month.ago) }
  scope :by_symbol, -> { group(:symbol) }
  scope :ordered_by, -> { order('count_id DESC').count('id') }

  protected
    def blank_field
      raise 'Empty Field For AllTimeHigh' if self.symbol.blank? || self.saved_on.blank?
    end
end

app/models/zack.rb
class Zack < ActiveRecord::Base

  private
    def self.remove_text
      where.not("surprise = ?", "NA")
    end

    def self.surprise(query)
      where("cast(surprise as money) >= ?" , "#{query}")
    end

    def self.reported
      where("cast(reported as float) >= 0")
    end
end

app/controllers/all_time_highs_controller.rb
class AllTimeHighsController < ApplicationController
  def index
    if params[:query].present?
      time_period = query_time_period(params[:query])
      @all_time_highs = AllTimeHigh.period(time_period).by_symbol.ordered_by
    else
      @all_time_highs = AllTimeHigh.monthly.by_symbol.ordered_by
    end
  end

  private
    def query_time_period(query)
      if query == 'bi_weekly'
        2.weeks.ago
      elsif query == 'weekly'
        1.week.ago
      else
        1.month.ago
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/briefings_earnings_controller.rb
class BriefingsEarningsController < ApplicationController
  def index
    @briefings_earnings = BriefingsEarning.earnings.expectation.surprise(params[:query])
  end
end

app/controllers/daily_high_lows_controller.rb
class DailyHighLowsController < ApplicationController
  def index
    @daily_difference = DailyHighLow.high_low_difference
  end
end

app/controllers/new_highs_controller.rb
class NewHighsController < ApplicationController
  def index
    if params[:query].present?
      time_period = query_time_period(params[:query])
      @new_highs = NewHigh.period(time_period).by_symbol.ordered_by
    else
      @new_highs = NewHigh.monthly.by_symbol.ordered_by
    end
  end

  private
    def query_time_period(query)
      if query == 'bi_weekly'
        2.weeks.ago
      elsif query == 'weekly'
        1.week.ago
      else
        1.month.ago
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/zacks_controller.rb
class ZacksController < ApplicationController
  def index
    @zacks_earnings = Zack.remove_text.surprise(params[:query]).reported
  end

  private
end

app/helpers/all_time_highs_helper.rb
module AllTimeHighsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/briefings_earnings_helper.rb
module BriefingsEarningsHelper
end

app/helpers/daily_high_lows_helper.rb
module DailyHighLowsHelper

  def high_low_chart
    diff_data = []
    @daily_difference.columns.each_with_index do |category_name, index|
      category_data = {}
      @daily_difference.rows.each do |raw_data_row|
        category_data[raw_data_row[5]] = raw_data_row[index] unless index == 5
      end
      unless category_name == 'saved_on'
        diff_data << { name: category_name, data:  category_data }
      end
    end
  line_chart diff_data
  end
end

app/helpers/new_highs_helper.rb
module NewHighsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/zacks_helper.rb
module ZacksHelper
end

app/views/all_time_highs/_table.html.erb
<table class="table table-striped all_time_highs">
  <tr>
    <th>Symbol:</th>
    <th>Occurances: </th>
  </tr>
  <% @all_time_highs.each do |highs| %>
    <tr>
      <td><%= highs[0] %></td>
      <td><%= highs[1] %></td>
    </tr>
  <% end %>
<table>

app/views/all_time_highs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <section>
        <div class="center well block-powder">
          <h1>Search All Time Highs</h1>
        </div>
      </section>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= button_to 'Weekly', all_time_highs_path, :method => :get, params: { query: :weekly }, remote: true, class: 'btn btn-primary' %>
    </div>
    <div class="col-md-4">
      <%= button_to 'Bi-Weekly', all_time_highs_path, :method => :get, params: { query: :bi_weekly }, remote: true, class: 'btn btn-primary' %>
    </div>
    <div class="col-md-4">
      <%= button_to 'Monthly', all_time_highs_path, :method => :get, params: { query: :monthly }, remote: true, class: 'btn btn-primary' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div id="all-time-highs">

      </div>
    </div>
  </div>
</div>

app/views/all_time_highs/index.js.erb
$('#all-time-highs').html("<%= j render 'table' %>")

app/views/briefings_earnings/_table.html.erb
<section class='table-responsive'>
  <table id="" class="table table-striped" >
    <tr>
      <th>Symbol:</th>
      <th>Earnings </th>
      <th>Expectation</th>
      <th>Year Ago Earnings</th>
      <th>Revenue</th>
      <th>Released</th>
    </tr>
      <% @briefings_earnings.each do |e| %>
        <tr>
          <td><%= e.symbol %></td>
          <td><%= e.earnings %></td>
          <td><%= e.expectation %></td>
          <td><%= e.year_ago_earnings %></td>
          <td><%= e.revenue %></td>
          <td><%= e.saved_on.strftime("%m-%d-%Y") %></td>
        </tr>
      <% end %>
    <table>
</section>

app/views/briefings_earnings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
       Usage: Earnings Expectation Beat- Search for earnings beat > value(ex: 25 for 25%,
       50 for 50%) Report Time is in M-D-Year format.
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <section id="search_earnings">
        <%= form_for briefings_path, method: :get, remote: true do %>
          <p>
            Earnings Surprise:
            <%= text_field_tag :query, params[:query] %>
            <%= submit_tag 'Search', name: nil %>
          </p>
        <% end %>
      </section>
      <div id="briefings-earnings">

      </div>
    </div>
  </div>
</div>

app/views/briefings_earnings/index.js.erb
$('#briefings-earnings').html("<%= j render 'table' %>")

app/views/daily_high_lows/index.html.erb
<div class="container">
  <div class="row">
    <div class="well">
      <p><h3 class='center'>Daily High Lows Difference</h3></p>
      <%= high_low_chart %>
    </div>
  </div>

  <div class="row">
    <article class="well block-powder">
      <p>
        Daily Tally of the difference between the number of stocks that have
        hit a new high vs. a new low over 5 time periods(1 month, 3 month,
        6 month, 12 month, and year to date).  Usage: Markets have periods of
        expansion and contraction. Being on the correct side of the market flow
        and awareness of potential turns is an invaluable tool for trade planning
        and execution.
      </p>
      <p>
        On shorter time frames markets expand and contract on swifter cycles.
        Longer term this smooths out.  Through analyzing higher time frames one
        can strategically be on the correct side of the order flow while on shorter
        time frames tactically aware.
      </p>
    </article>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Screener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/navbar' %> 
<%= yield %>

</body>
</html>

app/views/new_highs/_table.html.erb
<table class="table table-striped new_highs">
  <tr>
    <th>Symbol:</th>
    <th>Occurances: </th>
  </tr>
  <% @new_highs.each do |highs| %>
    <tr>
      <td><%= highs[0] %></td>
      <td><%= highs[1] %></td>
    </tr>
  <% end %>
<table>

app/views/new_highs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <section>
        <div class="center well block-powder">
          <h1>Search New Highs</h1>
        </div>
      </section>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= button_to 'Weekly', new_highs_path, :method => :get, params: { query: :weekly }, remote: true, class: 'btn btn-primary' %>
    </div>
    <div class="col-md-4">
      <%= button_to 'Bi-Weekly', new_highs_path, :method => :get, params: { query: :bi_weekly }, remote: true, class: 'btn btn-primary' %>
    </div>
    <div class="col-md-4">
      <%= button_to 'Monthly', new_highs_path, :method => :get, params: { query: :monthly }, remote: true, class: 'btn btn-primary' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div id="new_highs">

      </div>
    </div>
  </div>
</div>

app/views/new_highs/index.js.erb
$('#new_highs').html("<%= j render 'table' %>")

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Screener', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'New Highs', new_highs_path %></li>
        <li><%= link_to 'All Time Highs', all_time_highs_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Earnings <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Zacks Earnings', zacks_path %></li>
            <li><%= link_to 'Briefings Earnings', briefings_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'High-Low Breadth', daily_high_lows_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/static_pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <section>
        <div class="center well block-powder">
          <h1>Stock Screen Suite</h1>
        </div>
      </section>
    </div>
  </div>
  <div class="row">
    <section class="col-md-12">
      <p>
        Two known market anomolies are PEAD and Momentum.  Post Earnings Announcement
        Drift is a quantified market phenomenon where stocks that beat market participants
        expectations show a favorable post earnings drift as the new information is processed
        which can last for weeks, months, and cumulative quarters.  Momentum is an anomoly where
        a stocks that show strong price acculation over three, six, and twelve month periods continue
        to outperform the general market over these time frames moving forward.
      </p>
      <p>
        Market Breadth is taking the temperature of the overall market as gauged by the strength of
        the underlying stocks.  Through determining the stregnth of the overall market one can align
        themselves on the correct side of the order flow for their time frame with greater confidence.
      </p>
      <p>
        This screening utility takes a few of these concepts in order to
        gauge market health and curate watchlist with a
        focus on growth stocks as indicated by accelerating
        earnings and momentum stocks based upon accumulation of all time high
        and new highs over mutliple time frames.  The greater the number of stocks
        making new and all time highs the healthier the market.
      </p>
    </section>
  </div>
  <div class="row row-eq-height">
    <section class='row-eq-height'>
      <div class="col-md-4 block block-cream">
        <h3>High Low Breadth</h3>
        <%= image_tag('breadth.png') %>
        Chart showing the difference between stocks making new highs vs. new lows over
        5 different time frames to gauge market appetitie for swing trading.
      </div>
      <div class="col-md-4 block block-cream">
        <h3>Searchable Earnings</h3>
        <%= image_tag('search_earnings.png')%>
        Search for earnings that beat earnings expectations and previous quarter
        earnings.
      </div>
      <div class="col-md-4 block block-cream">
        <h3>All Time & 52-Week Highs</h3>
        <%= image_tag('all_time_high.png') %>
        Search for stocks making new highs and all time highs to curate watchlist.
        Three time frames available. Weeky, Bi-Weekly and Monthly.
      </div>
    </section>
  </div>
</div>

app/views/zacks/_table.html.erb
<section class='table-responsive'>
  <table id="" class="table table-striped" >
    <tr>
      <th>Symbol:</th>
      <th>Company </th>
      <th>Report Time</th>
      <th>Estimate</th>
      <th>Reported</th>
      <th>Surprise</th>
    </tr>
      <% @zacks_earnings.each do |e| %>
        <tr>
          <td><%= e.symbol %></td>
          <td><%= e.company %></td>
          <td><%= e.created_at.strftime("%m-%d-%Y") %></td>
          <td><%= e.estimate %></td>
          <td><%= e.reported %></td>
          <td><%= e.surprise %></td>
        </tr>
      <% end %>
    <table>
</section>

app/views/zacks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <section>
        <div class="center well block-powder">
          <h1>Search Earnings</h1>
        </div>
      </section>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <section class='well block-cream'>
        Usage: Enter surprise threshold, i.e. 25 for stocks with a surprise > 25%
      </section>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <section id="search_earnings">
        <%= form_for zacks_path, method: :get, remote: true do %>
          <p>
            Earnings Surprise:
            <%= text_field_tag :query, params[:query] %>
            <%= submit_tag 'Search', name: nil %>
          </p>
        <% end %>
      </section>
      <div id="zacks-earnings">

      </div>
    </div>
  </div>
</div>

app/views/zacks/index.js.erb
$('#zacks-earnings').html("<%= j render 'table' %>")